// Build-time codegen: embed each authoring skill's markdown into a TypeScript
// module so the npm package (which ships only dist/, never skills/) can serve
// the guidance over MCP. Run from `npm run build` BEFORE tsc, so dist/ never
// depends on skills/ at runtime and the embedded copy is regenerated fresh on
// every build (no stale hand-committed content). The generated module is also
// committed so `tsc --noEmit`, vitest and a bare `git clone` all resolve the
// import without a prior build; a test (test/guides.test.ts) asserts the
// committed copy still matches skills/ so drift is caught in CI.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** One MCP guidance topic mapped to the skill directory that backs it. The
 *  topic is the stable public enum value (get_authoring_guide's `topic`, and
 *  the prompt name is `lingochunk-<skill>`); the skill dir is where the
 *  markdown lives. Keep this the single source of truth for both. */
export const GUIDE_SOURCES: { topic: string; skill: string }[] = [
  { topic: "overview", skill: "lingochunk-overview" },
  { topic: "lesson", skill: "lingochunk-lesson" },
  { topic: "course", skill: "lingochunk-course" },
  { topic: "cards", skill: "lingochunk-cards" },
  { topic: "annotations", skill: "lingochunk-annotate" },
  { topic: "add-language", skill: "lingochunk-add-language" },
  { topic: "discuss", skill: "lingochunk-discuss" },
  { topic: "skill-author", skill: "lingochunk-skill-author" },
];

interface ParsedSkill {
  /** The frontmatter `name:` (used as the MCP prompt name). */
  name: string;
  /** The frontmatter `description:` (the prompt's description / trigger text). */
  description: string;
  /** The markdown body with the YAML frontmatter stripped. */
  body: string;
}

/** Split a SKILL.md into its frontmatter fields and body. The plugin-only YAML
 *  frontmatter (name/description = Claude Code trigger metadata) is dropped from
 *  the guide body — over MCP the tool/prompt description already carries the
 *  trigger — but `name` and `description` are lifted out for the prompt config. */
export function parseSkill(markdown: string): ParsedSkill {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(markdown);
  if (!match) {
    throw new Error("SKILL.md has no YAML frontmatter block");
  }
  const frontmatter = match[1]!;
  const body = markdown.slice(match[0].length).trim();
  const field = (key: string): string => {
    // Frontmatter values here are single-line (the description is one long
    // line). Match `key: value` up to the end of the line.
    const re = new RegExp(`^${key}:[ \\t]*(.+?)[ \\t]*$`, "m");
    const m = re.exec(frontmatter);
    if (!m) throw new Error(`SKILL.md frontmatter missing '${key}'`);
    return m[1]!.trim();
  };
  return { name: field("name"), description: field("description"), body };
}

/** Read + parse every skill listed in GUIDE_SOURCES, relative to the repo root
 *  (the parent of scripts/). */
export function loadGuides(): {
  topic: string;
  skill: string;
  parsed: ParsedSkill;
}[] {
  const repoRoot = fileURLToPath(new URL("..", import.meta.url));
  return GUIDE_SOURCES.map(({ topic, skill }) => {
    const path = `${repoRoot}skills/${skill}/SKILL.md`;
    const parsed = parseSkill(readFileSync(path, "utf8"));
    return { topic, skill, parsed };
  });
}

/** Render the generated module source. */
export function renderModule(): string {
  const guides = loadGuides();
  const topics = guides.map((g) => g.topic);
  const topicUnion = topics.map((t) => JSON.stringify(t)).join(" | ");
  const topicList = topics.map((t) => JSON.stringify(t)).join(", ");
  const entries = guides
    .map(({ topic, parsed }) => {
      return (
        `  ${JSON.stringify(topic)}: {\n` +
        `    topic: ${JSON.stringify(topic)},\n` +
        `    promptName: ${JSON.stringify(parsed.name)},\n` +
        `    description: ${JSON.stringify(parsed.description)},\n` +
        `    body: ${JSON.stringify(parsed.body)},\n` +
        `  },`
      );
    })
    .join("\n");

  return (
    "// AUTO-GENERATED by scripts/generate-guides.ts from skills/*/SKILL.md.\n" +
    "// Do not edit by hand: `npm run build` regenerates it. The authoring\n" +
    "// skills are embedded here because the npm package ships only dist/, so\n" +
    "// remote MCP clients cannot read skills/ off disk.\n" +
    "\n" +
    `export type GuideTopic = ${topicUnion};\n` +
    "\n" +
    "export interface Guide {\n" +
    "  /** The public topic value (get_authoring_guide's `topic` argument). */\n" +
    "  topic: GuideTopic;\n" +
    "  /** The MCP prompt name (`lingochunk-<skill>`). */\n" +
    "  promptName: string;\n" +
    "  /** One-line description / trigger text, from the skill frontmatter. */\n" +
    "  description: string;\n" +
    "  /** The full skill markdown, frontmatter stripped. */\n" +
    "  body: string;\n" +
    "}\n" +
    "\n" +
    `export const GUIDE_TOPICS: readonly GuideTopic[] = [${topicList}] as const;\n` +
    "\n" +
    "export const GUIDES: Record<GuideTopic, Guide> = {\n" +
    entries +
    "\n};\n"
  );
}

/** CLI entry: write src/generated/guides.ts. */
function main(): void {
  const outDir = fileURLToPath(new URL("../src/generated/", import.meta.url));
  const outPath = `${outDir}guides.ts`;
  const source = renderModule();
  mkdirSync(outDir, { recursive: true });
  writeFileSync(outPath, source);
  process.stdout.write(
    `generate-guides: wrote ${outPath} (${GUIDE_SOURCES.length} guides)\n`,
  );
}

// Only run when invoked directly (not when imported by the drift-guard test).
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
